### PR TITLE
Components, handlers, properties and style enums

### PR DESCRIPTION
**Pull request by sudhirvkumar**

### CODE REVIEW

**Comment by ohanhi** [comment]
Thank you for your contributions! Could you add a description for the PR? Also, is this based on #31?

**Comment by sudhirvkumar** [comment]
Yes I will add the description during my day. Yes, its partly based on #31 but heavily modified and a lot of other things have been added.

I would like to refactor further. I wanted your feedback or suggestions to make it even better.

**Comment by sudhirvkumar** [comment]
@ohanhi I want to really move fast towards production quality. We have started working on the UIExplorer project too. https://github.com/abinayasudhir/NativeUIExplorer

After using Elm I don't want to go through the process of using JavaScript to develop React Native Apps. Please let me know how we can move faster.

Any idea about getting `elm-native-ui` support in the elm compiler and core? What's the timeline like?

Is it possible to fast forward it after discussing with Evan?

I read your blog and you mentioned six months to one year. I really can't wait that long. I want to start building Mobile Apps with elm like yesterday! ;)

If its going to really take that long then I will have to fork and do a lot of other stuff to have a reliable dev environment... which I would like to avoid.

**Comment by sudhirvkumar** [comment]
Oops... now I have to resolve conflicts! @ohanhi because of my aggressive schedule to get it to production level. I will fork it and then we can merge once we are ready to spend some quality time merging. Will try to keep it as close as possible to the elm-html ways of doing things.

**Comment by ohanhi** [comment]
@sudhirvkumar This PR seems to conflict quite a bit with #31, which I just merged. It would really help us a ton if you could split this stuff into small (~200 line) pull requests with good descriptions -- that way it would be much less of an effort to go through what's happening there.

**Comment by sudhirvkumar** [comment]
@ohanhi Let me think about it a bit. I would really appreciate it... if you can merge PRs faster then I promise I will send you shorter PRs.

> If You Want To Go Fast, Go Alone. If You Want To Go Far, Go Together

I want to go fast now and go far after that. May be you can help me get the PRs merged faster or make me a member so I can merge it myself.

**Comment by sudhirvkumar** [comment]
Closing this PR. Will send smaller PRs and then lets see how it goes from there...

**Comment by mk** [comment]
@sudhirvkumar I'm also really excited for elm-native-ui and would love to ship an app with it soon!

After looking at how many properties etc there are in React Native we concluded that in order to maintain sanity and keep up to date with changes in React Native manually coding the elm files would not really work well. That's how we came up with the generator code in #31. Did you also follow this approach? If yes can you also commit the changes to the generating code (which we put in `generator/`?

**Comment by sudhirvkumar** [comment]
@mk I took your generated code and modified it. We are done with almost all the properties only a few are left. While working on UIExplorer we figured there are a few more properties/styles but very very few which can be handled manually.

I am a big fan of generators. In this case. I believe for every release of React Native version there are going to be minor changes and I don't think we need generators to generate code everytime. May be generators will be counter productive. As some of the properties I had to do custom work. for example `source` property.

Thanks for generators... we avoided typing a lot of code! ;)

I want to have the UIExplorer built and ready before this month end. From May I want to build iOS and Android Apps with Elm and not go through the Javascript Libraries and complex setup and npm gymnastics.

I forked the repo into https://github.com/elm-native/elm-native-ui. Please watch that repo.

I just want to move fast. So I am going to focus on getting it up and running ASAP.

@ohanhi Sorry if you felt that I was pushing you... I am just excited at the opportunity of being able to use Elm to build Native Mobile Apps.

With this done... I will be able to switch all the front end code to Elm ;) I am not even going to mention JavaScript to new Recruits. They will learn Elm and work with that for all Front End work!

**Pull request closed without merging**
