### PR TITLE
implementation of stylesheets

### LINKED ISSUE #17: Allow the StyleSheet.create method for styles
`StyleSheet.create` is the preferred way of providing styles in React Native ([docs](https://facebook.github.io/react-native/docs/style.html#content)).

### PR DESCRIPTION
**Pull request by gabrielperales**
This should close #17

### CODE REVIEW

**Comment by gabrielperales** [comment]
I have updated the counter example to test stylesheets, and seems to work.

You can try it here https://github.com/gabrielperales/elm-native-ui/tree/stylesheet-example

**Comment by ohanhi** [comment]
Thank you! 
The code seems reasonable to me in general. What were the design concerns you had about this?

**Comment by gabrielperales** [comment]
I did a new type and i called it as stylesheet, maybe it should have another name like styleId and the function to assign those could be stylesIds instead of stylesheet again

**Comment by ohanhi** [comment]
To me, an opaque type would make the most sense. So instead of
```elm
type alias StyleSheet =
    Int
```
we would have
```elm
type StyleSheet
    = StyleSheet Int
```

This would hide the details (of how the reference is passed) from the user and there would be no way to see that it's really just a number.

**Comment by gabrielperales** [comment]
Ok, if you are happy with that and you think the type names are Ok, I can just do those changes and remove the WIP status.

**Pull request merged**
