### PR TITLE
Generate Elements, Properties and Handlers from react-docgen

### PR DESCRIPTION
**Pull request by mk**
We're using the json output of react-docgen to generate Elements, Properties and Handlers.elm for the most common components (currently Text, Image, ActivityIndicator, MapView, Picker, ProgressBarAndroid, ProgressView, RefreshControl, ScrollView, SegmentedControl, Slider, StatusBar, Switch, SwitchAndroid, Switch, TabBar, ActivityIndicator, TextInput, Toolbar and View).

This also makes all enum properties safe on compile time.

We've used this fork to build Hangman in elm-native-ui: https://github.com/mk/hangman
You can also find the slides on the talk we gave on how this works at https://speakerdeck.com/mkvlr/building-hangman-in-elm-native-ui

Next up will be doing the same for Style.elm.

### CODE REVIEW

**Comment by ohanhi** [comment]
This is pretty darn great! I had a little bad luck trying this out on the weekend (React Native and npm acting up), but I'm trying my best to get this merged as soon as possible!

**Comment by mk** [comment]
This also seems to be my main issue when working on elm-native-ui at the moment as well. I'm spending quite a bit of time removing and recreating `node_modules/. I don't really have experience with React Native so I'm not sure if that's normal.

**Comment by ohanhi** [comment]
Sadly, it is.

**Comment by abinayasudhir** [comment]
@ohanhi @mk I am working on the Elements, Handlers and Properties. I have used a lot of code from this pull request.

Its available here

https://github.com/AtomicITS/elm-native-ui/pull/30

Will complete the rest of the stuff and then send you a pull request.

If you have any suggestions please let me know.

Thanks in Advance

**Comment by abinayasudhir** [comment]
@ohanhi @mk My Objective is to complete UIExplorer for at least Android components before this weekend. Lets see how it goes.

https://github.com/abinayasudhir/NativeUIExplorer

**Comment by eeue56** [comment]
Can someone explain the problem with node_modules to me? Maybe I can fix it.

**Comment by ohanhi** [comment]
@eeue56 No, the problem is that npm and/or react-native get things mangled up at random. So sometimes you just need to `rm -rf node_modules && npm install`.

**Pull request merged**
